config/routes.rb
Rails.application.routes.draw do
  require 'pry'

  root :to => 'application#index'
  get 'sitemap' => 'sitemap#index'

  get 'photography' => 'application#photography'
  scope "/photography" do
    photos = YAML.load_file("#{Rails.root}/config/photography.yml")
    photos.each do |name, data|
      get name.gsub("_", "-") => 'application#photo_page'
    end
  end

  get 'table' => 'application#table'
  scope "/table" do
    photos = YAML.load_file("#{Rails.root}/config/table.yml")
    photos.each do |name, data|
      get name.gsub("_", "-") => 'application#photo_page'
    end
  end

  get 'illustration' => 'application#illustration'
  scope "/illustration" do
    photos = YAML.load_file("#{Rails.root}/config/illustration.yml")
    photos.each do |name, data|
      get name.gsub("_", "-") => 'application#photo_page'
    end
  end

  get 'osx' => 'application#osx'
  scope "/osx" do
    photos = YAML.load_file("#{Rails.root}/config/osx.yml")
    photos.each do |name, data|
      get name.gsub("_", "-") => 'application#photo_page'
    end
  end

  get 'graphic-design' => 'application#graphic_design'
  scope "/graphic-design" do
    photos = YAML.load_file("#{Rails.root}/config/graphic-design.yml")
    photos.each do |name, data|
      get name.gsub("_", "-") => 'application#photo_page'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require "yaml"
  require 'uri'
  require 'miro'
  require 'mime/types'

  def index
    @metadata = {
      "title" => "Portfolio",
      "description" => "Explore Dave's best design and artwork across many mediums and practices.",
      "url" => "https://aslittledesign.com",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => "https://d2vez5w0ugqe83.cloudfront.net/open_graph/index.png",
        "type" => "image/png",
        "alt" => "Dave Scott McCarthy's Photography"
      }
    }
  end

  def photography
    photos = YAML.load_file("#{Rails.root}/config/photography.yml")

    @photos = photos.to_a.shuffle!.to_h
    @metadata = {
      "title" => "Photography",
      "description" => "Explore Dave's best photography work, from portraiture to landscape photos.",
      "url" => "https://aslittledesign.com/photography",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => "https://d2vez5w0ugqe83.cloudfront.net/open_graph/photography.png",
        "type" => "image/png",
        "alt" => "Dave Scott McCarthy's Photography"
      }
    }
  end

  def illustration
    @illustrations = YAML.load_file("#{Rails.root}/config/illustration.yml")

    @metadata = {
      "title" => "Illustration",
      "description" => "Explore Dave's best illustration work, from charcoal renderings to digital paintings.",
      "url" => "https://aslittledesign.com/illustration",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => "https://d2vez5w0ugqe83.cloudfront.net/open_graph/illustration.png",
        "type" => "image/png",
        "alt" => "Dave Scott McCarthy's Illustrations"
      }
    }
  end

  def table
    @examples = YAML.load_file("#{Rails.root}/config/table.yml")

    @metadata = {
      "title" => "Table.co",
      "description" => "Explore Dave's best graphic design work, from logos to watchfaces.",
      "url" => "https://aslittledesign.com/table",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => "https://d2vez5w0ugqe83.cloudfront.net/open_graph/table.png",
        "type" => "image/png",
        "alt" => "Dave Scott McCarthy's Graphic Design"
      }
    }
  end

  def graphic_design
    @graphics = YAML.load_file("#{Rails.root}/config/graphic-design.yml")

    @metadata = {
      "title" => "Graphic Design",
      "description" => "Explore Dave's best graphic design work, from logos to watchfaces.",
      "url" => "https://aslittledesign.com/graphic-design",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => "https://d2vez5w0ugqe83.cloudfront.net/open_graph/graphic-design.png",
        "type" => "image/png",
        "alt" => "Dave Scott McCarthy's Graphic Design"
      }
    }
  end

  def osx
    @mockups = YAML.load_file("#{Rails.root}/config/osx.yml")

    @metadata = {
      "title" => "OS X 'Everest'",
      "description" => "Explore Dave's concept for a new version of OS X, created before the reveal of OS X 10.10 'Yosemite'.",
      "url" => "https://aslittledesign.com/osx",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => "https://d2vez5w0ugqe83.cloudfront.net/open_graph/osx.png",
        "type" => "image/png",
        "alt" => "OS X 10.10 'Everest' Concept"
      }
    }
  end

  def photo_page
    uri = URI(request.original_url).path.split('/')
    @type = uri[-2]
    page = uri.last.gsub("-", "_")
    photos = YAML.load_file("#{Rails.root}/config/#{@type}.yml")

    @photo = photos[page]

    @metadata = {
      "title" => @photo["title"],
      "description" => @photo["description"].truncate(155),
      "url" => "https://aslittledesign.com/#{@type}/#{page}",
      "type" => "website",
      "card" => "summary_large_image",
      "image" => {
        "url" => @photo["url"],
        "type" => MIME::Types.type_for(File.extname(@photo["url"]).gsub(/\./, ""))[0].content_type,
        "alt" => "Image titled #{@photo["title"]}"
      }
    }
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil

  def index
    @photos = YAML.load_file("#{Rails.root}/config/photography.yml")
    @illustrations = YAML.load_file("#{Rails.root}/config/illustration.yml")
    @table_examples = YAML.load_file("#{Rails.root}/config/table.yml")
    @graphics = YAML.load_file("#{Rails.root}/config/graphic-design.yml")
    @osx_mockups = YAML.load_file("#{Rails.root}/config/osx.yml")

    @base_url = "https://aslittledesign.com"

    respond_to do |format|
      format.xml
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/graphic_design.html.haml
- content_for :page_style do "graphic_design" end
- content_for :scripts do
  = javascript_include_tag "pages/graphic_design"

- description = "Knowledge of Graphic Design is valuable in all facets of design, as it teaches a designer how to create order, balance, and beauty in a design."

= render "partials/gallery", :collection => @graphics, :locals => { :title => "Graphic Design", :description => description }

app/views/application/illustration.html.haml
- content_for :page_style do "illustration" end

- description = "My original major in college, Illustration remains a great way to both hone my creative skills, as well as to relax."

= render "partials/gallery", :collection => @illustrations, :locals => { :title => "Illustration", :description => description }

app/views/application/index.html.haml
- content_for :page_style do "index" end

- content_for :scripts do
  = javascript_include_tag "pages/index"

%section.fringe
  %h1
    .fringe--name.m-red(js-fringe="red") Dave Scott McCarthy
    .fringe--name.m-blue(js-fringe="blue") Dave Scott McCarthy
    .fringe--name(js-fringe="base") Dave Scott McCarthy

  .fringe--scroll.icon--arrow--down(js-scroll-down)
  
%section.biography.container
  = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/portrait-transparent.png", :class => "biography--photo"

  .biography--copy
    %h1.biography--title Hi, I'm Dave!
    %p I'm an interaction designer and front-end developer exploring the intersection between art and technology. I am always searching for the right way to speak with people in new and profound ways through the work I do.
    %p With a diverse artistic background and years of creating experiences for millions of people, I know the work I do can change lives around the world.

    .social
      .button.m-black.social--option(data-menu-toggle="follow")
        .button--content.m-icon.icon--connect
        .button--content Follow
        
      .button.m-black.social--option(data-menu-toggle="contact")
        .button--content.m-icon.icon--contact
        .button--content Contact

= render "partials/index_table"
= render "partials/index_photography"
= render "partials/index_illustration"
= render "partials/index_osx"
= render "partials/index_graphic_design"

app/views/application/osx.html.haml
- content_for :page_style do "osx" end

- description = "With the impending release of OS X 10.10 (codename 'Syrah') at WWDC, the operating system was expected to have an updated look, more closely in line with the aesthetic that iOS 7 brought to the iPhone.<br/><br/>This time around, I decided to take a stab at a conceptual redesign of the then current Mac operating system."

= render "partials/gallery", :collection => @mockups, :locals => { :title => "OS X 10.10 'Everest'", :description => description, :icon => "osx" }

app/views/application/photo_page.html.haml
- content_for :scripts do
  = javascript_include_tag "pages/photo_page"

- content_for :page_style do "photo_page" end

.container.page-intro
  = link_to (eval "#{@type}_path".gsub("-", "_")), :class => "button m-black page-intro--back" do
    %span.icon--arrow--left
    = @type.titleize

  %h1.page-intro--title= @photo["title"]  

.container.photo--container
  - image_class = "photo--image"
  - if @photo["transparent"]
    - image_class += " m-transparent"

  - if @photo["before"]
    = image_tag @photo["before"], :class => image_class, :"js-comparison" => "before"
    = image_tag @photo["url"], :class => image_class + " s-active", :"js-comparison" => "after"

  - else
    = image_tag @photo["url"], :class => image_class + " s-active"

- if @photo["before"]
  .container.toggle-comparison
    .button.m-black.toggle-comparison--toggle(js-toggle-comparison="before") Before
    .button.m-black.toggle-comparison--toggle.s-active(js-toggle-comparison="after") After

.container.photo--meta
  %p.photo--description= @photo["description"].html_safe

  .social
    .button.m-black.social--option(data-menu-toggle="share")
      .button--content.m-icon.icon--share
      .button--content Share

app/views/application/photography.html.haml
- content_for :page_style do "photography" end
- content_for :scripts do
  = javascript_include_tag "pages/photography"

.invisible(js-photo-info)
  - @photos.each do |key, value|
    %div(style="display: none")
      %div(js-info="identifier")= key
      %div(js-info="url")= value["thumb_url"]
      %div(js-info="title")= value["title"]
      - if value["orientation"]
        %div(js-info="orientation")= value["orientation"]

.page-intro.container
  = link_to root_path, :class => "button m-black m-back page-intro--back" do
    %span.icon--arrow--left
    %span Home

  %h1.page-intro--title Photography

.photos
  .photos--layout#photos

.social
  .button.m-black.social--option(data-menu-toggle="share")
    .button--content.m-icon.icon--share
    .button--content Share

app/views/application/table.html.haml
- content_for :page_style do "table" end

- description = "Table is a product designed to connect people with mentors through it's communication platform. As the lead designer, I worked with the team to bring consistency, and usability to our product and our brand. I worked on the design, direction, and development of the product, as well as started to build the design team."

= render "partials/gallery", :collection => @examples, :locals => { :title => "Table.co", :description => description }

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    - description = yield :description
    - canonical_url = yield :canonical_url

    = csrf_meta_tags

    %link(href="#{ canonical_url }" rel="canonical")

    =render "partials/meta"

    = yield :head

  %body
    %noscript
      .noscript.container
        This website
        %b will not
        work as intended without Javascript enabled. Here are  
        = link_to "instructions on how to enable Javascript in your web browser.", "http://www.enable-javascript.com/", :target => "_blank"

    .wrapper(js-blur="false")
      = yield
      = render "partials/footer"

    .pop(data-menu-wrapper)

    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag "pages/#{ yield :page_style }", media: 'all'
    = render "partials/scripts"    

app/views/partials/_footer.haml
%footer.footer.container
  =link_to root_path, :class => "footer--logo m-no-underline" do
    .icon--logo

  .footer--navigation
    = link_to photography_path, :class => "footer--link m-no-underline" do
      .footer--link-icon.icon--photography
      %small Photography

    = link_to table_path, :class => "footer--link m-no-underline" do
      .footer--link-icon.icon--table
      %small Table

    = link_to illustration_path, :class => "footer--link m-no-underline" do
      .footer--link-icon.icon--illustration
      %small Illustration

    = link_to osx_path, :class => "footer--link m-no-underline" do
      .footer--link-icon.icon--osx
      %small OS X

    = link_to graphic_design_path, :class => "footer--link m-no-underline" do
      .footer--link-icon.icon--graphic-design
      %small Graphic Design

  .footer--social
    .button.m-white.social--option(data-menu-toggle="follow")
      .button--content.m-icon.icon--connect
      .button--content Follow
      
    .button.m-white.social--option(data-menu-toggle="contact")
      .button--content.m-icon.icon--contact
      .button--content Contact

  %small.copyright
    &copy;
    = Time.now.year 
    David Scott McCarthy
    .copyright--rights All Rights Reserved

app/views/partials/_gallery.haml
.page-intro.container
  = link_to root_path, :class => "button m-black page-intro--back" do
    %span.icon--arrow--left
    Home

  %h1.page-intro--title= locals[:title]

- collection.each_with_index do |(key, value), index|
  .container.gallery-section(class="m-#{key}")
    - if key == "steve_jobs"
      .gallery-section--image
        .jobs--progress.m-first
        .jobs--progress.m-second
        .jobs--progress.m-last
        = image_tag value["url"], :class => "jobs--final"

    - else
      - image_class =
        - if value["transparent"] then "gallery-section--image m-transparent" else "gallery-section--image"

      = image_tag value["url"], :class => image_class

    .gallery-section--description
      %h2.gallery-section--title= value["title"]
      %p.gallery-section--body= truncate strip_tags(value["description"]), :length => 120, :separator => " "

      = link_to value["cta"] || value["title"], (eval "#{key}_path"), :class => "button m-black gallery-section--cta"

.social
  .button.m-black.social--option(data-menu-toggle="share")
    .button--content.m-icon.icon--share
    .button--content Share

app/views/partials/_index_graphic_design.haml
- description = "Graphic design can teach skills that reach far beyond just graphics. It teaches a designer how to create order, balance, and beauty in their designs.<br/><br/>Through it, I have continuously improved my ability to organize information, set type so it's both readable and aesthetically pleasing, and compose layouts in a way that's both beautiful and functional."

- image_el = capture_haml do
  = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/graphic-design.svg", :class => "section--image"

= render "partials/index_section", :locals => { :number => "05", :title => "Graphic Design", :description => description, :path => graphic_design_path, :icon => "graphic-design", :image_el => image_el }

app/views/partials/_index_illustration.haml
- description = "Illustration gives me the ability to communicate new ideas or invent new worlds purely from the imagination. Impossible situations, places, and ideas can be created at my will.<br/><br/>Illustration taught me to be detail-oriented, and through that, I discovered the incredible feeling of completing a piece after weeks of hard work."

- image_el = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/illustration.png", :class => "section--image"

= render "partials/index_section", :locals => { :number => "03", :title => "Illustration", :description => description, :path => illustration_path, :icon => "illustration", :image_el => image_el }

app/views/partials/_index_osx.haml
- description = "With the then impending release of OS X 10.10 (codename 'Syrah') at WWDC, OS X was expected to adopt an aesthetic resembling what iOS 7 brought to the iPhone.<br/><br/>Early in 2014, I decided to take a stab at a conceptual redesign of the current Mac operating system."

- image_el = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/osx.png", :class => "section--image"

= render "partials/index_section", :locals => { :number => "04", :title => "OS X 'Everest' Concept", :description => description, :path => osx_path, :icon => "osx", :image_el => image_el }

app/views/partials/_index_photography.haml
- description = "Photography is incredibly important to me. The pivotal moment I decided to be a creative professional was in High School. Over those four years, I learned to use Photoshop and Illustrator, and how to capture and compose images. I illustrated my first digital paintings, and even created composite images to drive narratives in my work. <br/><br/>I felt limitless, and that feeling has continued with me. Photography places me within the moment, and allows me to connect with the world from a perspective I wouldn't otherwise know."

- image_el = capture_haml do
  .viewfinder
    .viewfinder--top
      .viewfinder--top-icon.icon--viewfinder--fhd-60
      .viewfinder--top-time
        %span 12
        %small m
        %span 36
        %small s
      .viewfinder--chip
        .icon--viewfinder--chip-1
        .icon--viewfinder--arrow-up
      .viewfinder--chip
        .icon--viewfinder--chip-2
      .viewfinder--top-icon.icon--viewfinder--l
      .viewfinder--top-icon.icon--viewfinder--n

    .viewfinder--image-container
      = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/photography/background.png", class: "viewfinder--image-layer", :"js-parallax" => "background"
      = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/photography/midground.png", class: "viewfinder--image-layer", :"js-parallax" => "midground"
      = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/photography/foreground.png", class: "viewfinder--image-layer m-foreground", :"js-parallax" => "foreground"

      .viewfinder--exposure-overlay(js-viewfinder-exposure)

      .viewfinder--overlay(js-viewfinder-overlay)
        .viewfinder--overlay-grid.m-vertical
          .viewfinder--overlay-line
          .viewfinder--overlay-line
          .viewfinder--overlay-line
          .viewfinder--overlay-line
          .viewfinder--overlay-line
          .viewfinder--overlay-line

        .viewfinder--overlay-grid.m-horizontal
          .viewfinder--overlay-line
          .viewfinder--overlay-line
          .viewfinder--overlay-line.m-green
          .viewfinder--overlay-line

        .viewfinder--center

        .viewfinder--exposure
          .viewfinder--exposure-icon.icon--viewfinder--exposure
          
          .viewfinder--frames-icon.icon--viewfinder--frames

          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label 3
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label 2
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label 1
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label 0
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label -1
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label -2
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch
          .viewfinder--exposure-notch.m-labeled
            .viewfinder--exposure-notch-label -3

          %input(type="range" min="0" max="16" value="0" js-slider="exposure" orient="vertical" class="viewfinder--exposure-input--original")

        .viewfinder--right
          .icon--viewfinder--v-film
          .icon--viewfinder--dr-200

        .viewfinder--focus
          .viewfinder--focus-labels
            .viewfinder--focus-label.m-small 0.1
            .viewfinder--focus-label.m-medium 0.5
            .viewfinder--focus-label 1.0
            .viewfinder--focus-label 2.0
            .viewfinder--focus-label 3.0
            .viewfinder--focus-label 5.0
            .viewfinder--focus-label 10
            .viewfinder--focus-label.m-medium 20
            .viewfinder--focus-label.m-small
              %span.m-infinity ∞
              %span.m-subscript m
          %input(type="range" min="0" max="100" value="80" js-slider="focus")

        .viewfinder--icon-manual-focus.icon--viewfinder--manual-focus

        
    .viewfinder--bottom
      .viewfinder--bottom-icon.m-m.m-large.icon--viewfinder--m
      .viewfinder--bottom-icon.m-large.icon--viewfinder--brackets
      .viewfinder--bottom-icon.m-shutter-speed.icon--viewfinder--shutter-speed
      .viewfinder--bottom-text.m-large.m-blue 1000
      .viewfinder--bottom-text.m-small.m-blue F
      .viewfinder--bottom-text.m-large.m-blue 5.6
      .viewfinder--bottom-icon.m-exposure.icon--viewfinder--exposure
      .viewfinder--bottom-text.m-plus +
      .viewfinder--bottom-text.m-large 1.0
      .viewfinder--bottom-text.m-small ISO
      .viewfinder--bottom-text.m-large 400
      .viewfinder--icon-battery.icon--viewfinder--battery

= render "partials/index_section", :locals => { :number => "02", :title => "Photography", :description => description, :path => photography_path, :icon => "photography", :image_el => image_el }

app/views/partials/_index_section.haml
%section.section.table
  .section--copy
    -# .section--copy-number= locals[:number]
    %h2.section--copy-title= locals[:title]
    %p.section--copy-body= locals[:description].html_safe
    = link_to locals[:title], locals[:path], :class => "button m-black section--cta"

  = locals[:image_el]

  %p.section--copy-body.container.m-mobile= locals[:description].html_safe
  
  = link_to locals[:title], locals[:path], :class => "button m-black m-mobile section--cta"

app/views/partials/_index_table.haml
- description = "As the Lead Designer, I helped bring greater usability and consistency to our platform by building a visual language and unifying the experience of using the product. <br/><br/> From art direction and interface design to graphic design and front-end development, I worked to establish a design team, create extraordinary experiences, and connect with people using Table."

- image_el = capture_haml do
  .section--image
    = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/table.png", :class => "table-image"
    = image_tag "https://d2vez5w0ugqe83.cloudfront.net/index/table-animation.gif", :class => "table-image--animation"

= render "partials/index_section", :locals => { :number => "01", :title => "Table.co", :description => description, :path => table_path, :icon => "table", :image_el => image_el }

app/views/partials/_scripts.haml
= javascript_include_tag 'application'
= yield :scripts

-# Social scripts
= javascript_include_tag "//platform.twitter.com/widgets.js", :async => "true", :charset => "utf-8"

:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1109924649062219',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

= render "utilities/analytics"

app/views/sitemap/index.xml.haml
!!! XML
%urlset(xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd")
  %url
    %loc #{@base_url}/
    %priority 1.0
    %lastmod 2016-10-15
    %changefreq monthly

  %url
    %loc #{@base_url}/photography
    %priority 0.7
    %lastmod 2016-10-15
    %changefreq monthly

  %url
    %loc #{@base_url}/illustration
    %priority 0.9
    %lastmod 2016-10-15
    %changefreq monthly

  %url
    %loc #{@base_url}/table
    %priority 0.7
    %lastmod 2016-10-15
    %changefreq monthly

  %url
    %loc #{@base_url}/graphic-design
    %priority 0.9
    %lastmod 2016-10-15
    %changefreq monthly

  %url
    %loc #{@base_url}/osx
    %priority 0.5
    %lastmod 2016-10-15
    %changefreq monthly

  - @photos.each do |name, data|
    - formatted_name = name.gsub("_", "-")
    %url
      %loc #{@base_url}/photography/#{formatted_name}
      %priority 0.4
      %lastmod= data["last_modified"] || 2016-10-12
      %changefreq monthly

  - @illustrations.each do |name, data|
    - formatted_name = name.gsub("_", "-")
    %url
      %loc #{@base_url}/illustration/#{formatted_name}
      %priority 0.4
      %lastmod= data["last_modified"] || 2016-10-12
      %changefreq monthly

  - @table_examples.each do |name, data|
    - formatted_name = name.gsub("_", "-")
    %url
      %loc #{@base_url}/table/#{formatted_name}
      %priority 0.4
      %lastmod= data["last_modified"] || 2016-10-12
      %changefreq monthly

  - @graphics.each do |name, data|
    - formatted_name = name.gsub("_", "-")
    %url
      %loc #{@base_url}/graphic-design/#{formatted_name}
      %priority 0.4
      %lastmod= data["last_modified"] || 2016-10-12
      %changefreq monthly

  - @osx_mockups.each do |name, data|
    - formatted_name = name.gsub("_", "-")
    %url
      %loc #{@base_url}/osx/#{formatted_name}
      %priority 0.4
      %lastmod= data["last_modified"] || 2016-10-12
      %changefreq monthly

app/views/utilities/_analytics.haml
= render "utilities/analytics/ga"

app/views/utilities/analytics/_ga.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50872917-1', 'auto');
  ga('require', 'linkid');
  ga('send', 'pageview');